import { Roboto } from "next/font/google";
import "./globals.css";
import Header from '../components/layout/Header'
import Sessionprovider from "./lib/Sessionprovider";

const roboto = Roboto({ subsets: ["latin"],weight:['400','500','700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Sessionprovider>
      <main className="max-w-4xl mx-auto border p-4">   
      <Header/> 
      {children}
      </main>
      </Sessionprovider>
      </body>
    </html>
  );
}
